"""add index

Revision ID: 05d5c9e12e68
Revises: 5ae88e687085
Create Date: 2022-09-16 12:28:30.868893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d5c9e12e68'
down_revision = '5ae88e687085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gene_expressions_cancer_type'), 'gene_expressions', ['cancer_type'], unique=False)
    op.create_index(op.f('ix_gene_expressions_dataset'), 'gene_expressions', ['dataset'], unique=False)
    op.create_index(op.f('ix_mutations_cancer_type'), 'mutations', ['cancer_type'], unique=False)
    op.create_index(op.f('ix_mutations_dataset'), 'mutations', ['dataset'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutations_dataset'), table_name='mutations')
    op.drop_index(op.f('ix_mutations_cancer_type'), table_name='mutations')
    op.drop_index(op.f('ix_gene_expressions_dataset'), table_name='gene_expressions')
    op.drop_index(op.f('ix_gene_expressions_cancer_type'), table_name='gene_expressions')
    # ### end Alembic commands ###
