"""add gene expression migration

Revision ID: 11c2b7b96857
Revises: 27a19992d12e
Create Date: 2022-05-08 12:12:12.990963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c2b7b96857'
down_revision = '27a19992d12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_expressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_drug_name', sa.String(length=64), nullable=True),
    sa.Column('gene', sa.String(length=64), nullable=True),
    sa.Column('dataset', sa.String(length=32), nullable=True),
    sa.Column('cancer_type', sa.String(length=64), nullable=True),
    sa.Column('pvalue', sa.Float(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('provided_pvalue', sa.Float(), nullable=True),
    sa.Column('provided_correlation', sa.Float(), nullable=True),
    sa.Column('n_cell_line', sa.Integer(), nullable=True),
    sa.Column('provided_n_cell_line', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genes.gene_name'], ),
    sa.ForeignKeyConstraint(['standard_drug_name'], ['drugs.standard_drug_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gene_expressions')
    # ### end Alembic commands ###
