"""add foreign keys in mutations table

Revision ID: 27a19992d12e
Revises: 63bd2caec49b
Create Date: 2022-05-07 21:55:15.532822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a19992d12e'
down_revision = '63bd2caec49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mutations', 'genes', ['gene'], ['gene_name'])
    op.create_foreign_key(None, 'mutations', 'drugs', ['standard_drug_name'], ['standard_drug_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mutations', type_='foreignkey')
    op.drop_constraint(None, 'mutations', type_='foreignkey')
    # ### end Alembic commands ###
