"""update provided_sensitivity_scores table

Revision ID: 388a7a7008e5
Revises: 7fbbb22a3a89
Create Date: 2022-05-07 20:06:34.469559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388a7a7008e5'
down_revision = '7fbbb22a3a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provided_sensitivity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exp_id', sa.Integer(), nullable=False),
    sa.Column('ic50_provided', sa.Float(), nullable=True),
    sa.Column('auc_provided', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exp_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provided_sensitivity_scores')
    # ### end Alembic commands ###
