"""add omicprofiles table

Revision ID: 40a5d462a725
Revises: 12318176de56
Create Date: 2022-06-13 21:47:32.835493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a5d462a725'
down_revision = '12318176de56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('omics_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cellosaurus_id', sa.String(length=64), nullable=False),
    sa.Column('gene', sa.String(length=64), nullable=True),
    sa.Column('values', sa.Float(), nullable=True),
    sa.Column('score', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cellosaurus_id'], ['cell_lines.cellosaurus_id'], ),
    sa.ForeignKeyConstraint(['gene'], ['genes.gene_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('omics_profiles')
    # ### end Alembic commands ###
