"""add omicprofiles table

Revision ID: 4fca013cf4f0
Revises: 5396d8cd1409
Create Date: 2022-06-13 15:38:56.803859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fca013cf4f0'
down_revision = '5396d8cd1409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('0mics_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cellosaurus_id', sa.String(length=64), nullable=False),
    sa.Column('gene', sa.String(length=64), nullable=True),
    sa.Column('values', sa.Float(), nullable=True),
    sa.Column('score', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cellosaurus_id'], ['cell_lines.cellosaurus_id'], ),
    sa.ForeignKeyConstraint(['gene'], ['genes.gene_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('0mics_profiles')
    # ### end Alembic commands ###
