"""add gene index

Revision ID: 5396d8cd1409
Revises: 52a62931632b
Create Date: 2022-06-12 21:42:41.771325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5396d8cd1409'
down_revision = '52a62931632b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mut_exp_metadata_gene'), 'mut_exp_metadata', ['gene'], unique=False)
    op.drop_constraint('mut_exp_metadata_ibfk_1', 'mut_exp_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'mut_exp_metadata', 'genes', ['gene'], ['gene_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mut_exp_metadata', type_='foreignkey')
    op.create_foreign_key('mut_exp_metadata_ibfk_1', 'mut_exp_metadata', 'cell_lines', ['cellosaurus_index'], ['cellosaurus_index'])
    op.drop_index(op.f('ix_mut_exp_metadata_gene'), table_name='mut_exp_metadata')
    # ### end Alembic commands ###
