"""add omicprofiles table

Revision ID: 581ce91393fd
Revises: 40a5d462a725
Create Date: 2022-06-14 11:09:05.894549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581ce91393fd'
down_revision = '40a5d462a725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('omics_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cellosaurus_id', sa.String(length=64), nullable=False),
    sa.Column('gene', sa.String(length=64), nullable=True),
    sa.Column('values', sa.Float(), nullable=True),
    sa.Column('score', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cellosaurus_id'], ['cell_lines.cellosaurus_id'], ),
    sa.ForeignKeyConstraint(['gene'], ['genes.gene_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('omics_profiles')
    # ### end Alembic commands ###
