"""temporary drop foreign keys in mutations table

Revision ID: 63bd2caec49b
Revises: a973acff8fb1
Create Date: 2022-05-07 21:51:50.908950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bd2caec49b'
down_revision = 'a973acff8fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_drug_name', sa.String(length=64), nullable=True),
    sa.Column('gene', sa.String(length=64), nullable=True),
    sa.Column('dataset', sa.String(length=32), nullable=True),
    sa.Column('cancer_type', sa.String(length=64), nullable=True),
    sa.Column('pvalue', sa.Float(), nullable=True),
    sa.Column('statistic', sa.Float(), nullable=True),
    sa.Column('provided_pvalue', sa.Float(), nullable=True),
    sa.Column('provided_statistic', sa.Float(), nullable=True),
    sa.Column('n_mut', sa.Integer(), nullable=True),
    sa.Column('n_wt', sa.Integer(), nullable=True),
    sa.Column('provided_n_mut', sa.Integer(), nullable=True),
    sa.Column('provided_n_wt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mutations')
    # ### end Alembic commands ###
