"""update provided_sensitivity_scores table

Revision ID: 7fbbb22a3a89
Revises: bc6ff5a226bc
Create Date: 2022-05-07 20:04:01.525014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbbb22a3a89'
down_revision = 'bc6ff5a226bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provided_sensitivity_scores', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provided_sensitivity_scores', 'id')
    # ### end Alembic commands ###
