"""update mutations and gene_expressions tables

Revision ID: a973acff8fb1
Revises: 388a7a7008e5
Create Date: 2022-05-07 20:14:03.657189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a973acff8fb1'
down_revision = '388a7a7008e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene_expressions', sa.Column('n_cell_line', sa.Integer(), nullable=True))
    op.add_column('gene_expressions', sa.Column('provided_n_cell_line', sa.Integer(), nullable=True))
    op.add_column('mutations', sa.Column('n_mut', sa.Integer(), nullable=True))
    op.add_column('mutations', sa.Column('n_wt', sa.Integer(), nullable=True))
    op.add_column('mutations', sa.Column('provided_n_mut', sa.Integer(), nullable=True))
    op.add_column('mutations', sa.Column('provided_n_wt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mutations', 'provided_n_wt')
    op.drop_column('mutations', 'provided_n_mut')
    op.drop_column('mutations', 'n_wt')
    op.drop_column('mutations', 'n_mut')
    op.drop_column('gene_expressions', 'provided_n_cell_line')
    op.drop_column('gene_expressions', 'n_cell_line')
    # ### end Alembic commands ###
