"""update jags_samplings table

Revision ID: bc6ff5a226bc
Revises: fe65d23ce1ec
Create Date: 2022-05-07 19:45:12.772605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc6ff5a226bc'
down_revision = 'fe65d23ce1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jags_samplings', sa.Column('einf_HDI_high', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('einf_HDI_low', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('einf_mode', sa.Float(), nullable=True))
    op.drop_column('jags_samplings', 'ecinf_HDI_low')
    op.drop_column('jags_samplings', 'ecinf_HDI_high')
    op.drop_column('jags_samplings', 'ecinf_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jags_samplings', sa.Column('ecinf_mode', mysql.FLOAT(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ecinf_HDI_high', mysql.FLOAT(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ecinf_HDI_low', mysql.FLOAT(), nullable=True))
    op.drop_column('jags_samplings', 'einf_mode')
    op.drop_column('jags_samplings', 'einf_HDI_low')
    op.drop_column('jags_samplings', 'einf_HDI_high')
    # ### end Alembic commands ###
