"""update index

Revision ID: c7a98ca23bdd
Revises: 1c0d8f92a77d
Create Date: 2022-05-13 21:12:28.295845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a98ca23bdd'
down_revision = '1c0d8f92a77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mutations_cancer_type'), 'mutations', ['cancer_type'], unique=False)
    op.create_index(op.f('ix_mutations_dataset'), 'mutations', ['dataset'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutations_dataset'), table_name='mutations')
    op.drop_index(op.f('ix_mutations_cancer_type'), table_name='mutations')
    # ### end Alembic commands ###
