"""update jags_samplings table

Revision ID: fe65d23ce1ec
Revises: a29432bc3991
Create Date: 2022-05-07 19:42:21.195298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe65d23ce1ec'
down_revision = 'a29432bc3991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jags_samplings', sa.Column('auc_HDI_high', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('auc_HDI_low', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('auc_mode', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('beta1_HDI_high', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('beta1_HDI_low', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ec50_HDI_high', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ec50_HDI_low', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ec50_mode', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ecinf_HDI_high', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ecinf_HDI_low', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ecinf_mode', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('fitted_mae', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ic90_HDI_high', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ic90_HDI_low', sa.Float(), nullable=True))
    op.add_column('jags_samplings', sa.Column('ic90_mode', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jags_samplings', 'ic90_mode')
    op.drop_column('jags_samplings', 'ic90_HDI_low')
    op.drop_column('jags_samplings', 'ic90_HDI_high')
    op.drop_column('jags_samplings', 'fitted_mae')
    op.drop_column('jags_samplings', 'ecinf_mode')
    op.drop_column('jags_samplings', 'ecinf_HDI_low')
    op.drop_column('jags_samplings', 'ecinf_HDI_high')
    op.drop_column('jags_samplings', 'ec50_mode')
    op.drop_column('jags_samplings', 'ec50_HDI_low')
    op.drop_column('jags_samplings', 'ec50_HDI_high')
    op.drop_column('jags_samplings', 'beta1_HDI_low')
    op.drop_column('jags_samplings', 'beta1_HDI_high')
    op.drop_column('jags_samplings', 'auc_mode')
    op.drop_column('jags_samplings', 'auc_HDI_low')
    op.drop_column('jags_samplings', 'auc_HDI_high')
    # ### end Alembic commands ###
